// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxxccnagqnkgtoeubmtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4eGNjbmFncW5rZ3RvZXVibXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjE3NTQsImV4cCI6MjA2NDE5Nzc1NH0.HOOOv_QL-znxDY_ncPeV59UvnZpf873aurUHuuBpPr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);